//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUCrtPortBelly
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CuerpoFactura
    {
        [ScaffoldColumn(false)]
        public int crf_id { get; set; }
        [ScaffoldColumn(false)]
        public int cbf_id { get; set; }
        [ScaffoldColumn(false)]
        public int car_id { get; set; }
    
        public virtual CabezaFactura CabezaFactura { get; set; }
        public virtual Carrito Carrito { get; set; }
    }
}
