//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUCrtPortBelly
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductoEnCarrito
    {
        [ScaffoldColumn(false)]
        public int pcr_id { get; set; }
        [ScaffoldColumn(false)]
        public int car_id { get; set; }
        [ScaffoldColumn(false)]
        public int prd_id { get; set; }
        [DataType(DataType.Text)]
        [Display(Name = "Estado")]
        [Editable(false)]
        public string pcr_est { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "La cantidad debe ser mayor a cero.")]
        [Required(ErrorMessage = "La cantidad es requerida"),]
        [Display(Name = "Cantidad")]
        public int pcr_cnt { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [Display(Name = "Creado")]
        public System.DateTime pcr_dateOfCreated { get; set; }
    
        public virtual Carrito Carrito { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
